/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 22 08:49:30 GMT 2022
 */

package newjdkname;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import newjdkname.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ArrayList_ESTest_2 extends ArrayList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ArrayList<ArrayList<Object>> arrayList0 = new ArrayList<ArrayList<Object>>(0);
      ArrayList<ArrayList<Object>> arrayList1 = new ArrayList<ArrayList<Object>>(arrayList0);
      assertTrue(arrayList1.isEmpty());
  }
}
