/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 11 13:41:45 GMT 2022
 */

package org.elasticsearch.action.index;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.Map;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.client.Requests;
import org.elasticsearch.common.xcontent.XContentType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class IndexRequest_ESTest_3 extends IndexRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XContentType xContentType0 = XContentType.JSON;
      HashMap<XContentType, XContentType> hashMap0 = new HashMap<XContentType, XContentType>();
      IndexRequest indexRequest0 = new IndexRequest(".[+r%E(X 4[v!", ".[+r%E(X 4[v!");
      IndexRequest indexRequest1 = indexRequest0.source((Map) hashMap0, xContentType0);
      assertFalse(indexRequest1.isRetry());
      assertEquals((-3L), indexRequest1.version());
      assertEquals((-1L), indexRequest1.getAutoGeneratedTimestamp());
  }
}
