/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 11 13:41:45 GMT 2022
 */

package org.elasticsearch.action.index;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.Map;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.client.Requests;
import org.elasticsearch.common.xcontent.XContentType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class IndexRequest_ESTest_0 extends IndexRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IndexRequest indexRequest0 = new IndexRequest("", "", "n/a, actual length: [");
      assertEquals((-3L), indexRequest0.version());
      assertFalse(indexRequest0.isRetry());
      assertEquals("", indexRequest0.type());
      assertEquals("n/a, actual length: [", indexRequest0.id());
      assertEquals((-1L), indexRequest0.getAutoGeneratedTimestamp());
      assertEquals("", indexRequest0.index());
  }
}
