/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 18 07:09:23 GMT 2022
 */

package com.google.gwt.core.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.gwt.core.client.GWT;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class GWT_ESTest_0 extends GWT_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GWT gWT0 = new GWT();
      assertEquals("", gWT0.getUniqueThreadId());
  }
}
