/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 06 13:03:13 GMT 2023
 */

package cern.colt.matrix.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cern.colt.matrix.DoubleMatrix1D;
import cern.colt.matrix.impl.DenseDoubleMatrix1D;
import cern.colt.matrix.impl.SelectedDenseDoubleMatrix1D;
import cern.colt.matrix.impl.SparseDoubleMatrix1D;
import cern.colt.matrix.impl.WrapperDoubleMatrix1D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DenseDoubleMatrix1D_ESTest_2 extends DenseDoubleMatrix1D_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      double[] doubleArray0 = new double[7];
      DenseDoubleMatrix1D denseDoubleMatrix1D0 = new DenseDoubleMatrix1D(0, doubleArray0, 0, 0);
      int[] intArray0 = new int[2];
      SelectedDenseDoubleMatrix1D selectedDenseDoubleMatrix1D0 = new SelectedDenseDoubleMatrix1D(0, doubleArray0, 7, 0, intArray0, 0);
      WrapperDoubleMatrix1D wrapperDoubleMatrix1D0 = new WrapperDoubleMatrix1D(selectedDenseDoubleMatrix1D0);
      DoubleMatrix1D doubleMatrix1D0 = denseDoubleMatrix1D0.assign((DoubleMatrix1D) wrapperDoubleMatrix1D0);
      assertSame(denseDoubleMatrix1D0, doubleMatrix1D0);
  }
}
