/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 12 07:33:19 GMT 2022
 */

package weka.core;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockRandom;
import org.junit.runner.RunWith;
import weka.core.AlgVector;
import weka.core.Attribute;
import weka.core.BinarySparseInstance;
import weka.core.Instances;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class AlgVector_ESTest_4 extends AlgVector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AlgVector algVector0 = new AlgVector(0);
      AlgVector algVector1 = algVector0.add(algVector0);
      assertNotSame(algVector1, algVector0);
      assertEquals(0, algVector1.numElements());
  }
}
