/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 12 07:33:19 GMT 2022
 */

package weka.core;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockRandom;
import org.junit.runner.RunWith;
import weka.core.AlgVector;
import weka.core.Attribute;
import weka.core.BinarySparseInstance;
import weka.core.Instances;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class AlgVector_ESTest_9 extends AlgVector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ArrayList<Attribute> arrayList0 = new ArrayList<Attribute>();
      Instances instances0 = new Instances("DJn{+mw|lOSxc#", arrayList0, 8);
      MockRandom mockRandom0 = new MockRandom();
      AlgVector algVector0 = new AlgVector(instances0, mockRandom0);
      AlgVector algVector1 = algVector0.add(algVector0);
      assertNull(algVector1);
  }
}
