import org.elasticsearch.action.index.*;
import org.elasticsearch.ElasticsearchGenerationException;
import org.elasticsearch.Version;
import org.elasticsearch.action.ActionRequestValidationException;
import org.elasticsearch.action.CompositeIndicesRequest;
import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.RoutingMissingException;
import org.elasticsearch.action.support.replication.ReplicatedWriteRequest;
import org.elasticsearch.action.support.replication.ReplicationRequest;
import org.elasticsearch.client.Requests;
import org.elasticsearch.cluster.metadata.MappingMetaData;
import org.elasticsearch.cluster.metadata.MetaData;
import org.elasticsearch.common.Nullable;
import org.elasticsearch.common.UUIDs;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.io.stream.StreamOutput;
import org.elasticsearch.common.lucene.uid.Versions;
import org.elasticsearch.common.unit.ByteSizeValue;
import org.elasticsearch.common.unit.TimeValue;
import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.common.xcontent.XContentFactory;
import org.elasticsearch.common.xcontent.XContentHelper;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.IndexSettings;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.shard.ShardId;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import static org.elasticsearch.action.ValidateActions.addValidationError;
import java.util.*;

import org.elasticsearch.Version;
import org.elasticsearch.action.ActionRequestValidationException;
import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.support.ActiveShardCount;
import org.elasticsearch.action.support.replication.ReplicationResponse;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.io.stream.BytesStreamOutput;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.unit.ByteSizeValue;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.seqno.SequenceNumbers;
import org.elasticsearch.index.shard.ShardId;
import org.elasticsearch.rest.RestStatus;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import static org.junit.Assert.*;
import org.junit.Test;

import org.junit.*;


public class CodexTest_0_4_65 { 
  @Test
    public void testParent() {
        String parent = "parent";
        String name = "name";
        String path = "path";
        String fullPath = "fullPath";
        String id = "id";
        String type = "type";
        String version = "version";
        String state = "state";
        String source = "source";
        long versionLong = 1;
        long versionTypeLong = 2;
        long seqNo = 3;
        long primaryTerm = 4;
        long versionLong2 = 5;
        long versionTypeLong2 = 6;
        long seqNo2 = 7;
        long primaryTerm2 = 8;
        long versionLong3 = 9;
        long versionTypeLong3 = 10;
        long seqNo3 = 11;
        long primaryTerm3 = 12;
        long versionLong4 = 13;
        long versionTypeLong4 = 14;
        long seqNo4 = 15;
        long primaryTerm4 = 16;
        long versionLong5 = 17;
        long versionTypeLong5 = 18;
        long seqNo5 = 19;
        long primaryTerm5 = 20;
        long versionLong6 = 21;
        long versionTypeLong6 = 22;
        long seqNo6 = 23;
        long primaryTerm6 = 24;
        long versionLong7 = 25;
        long versionTypeLong7 = 26;
        long seqNo7 = 27;
        long primaryTerm7 = 28;
        long versionLong8 = 29;
        long versionTypeLong8 = 30;
        long seqNo8 = 31;
        long primaryTerm8 = 32;
        long versionLong9 = 33;
        long versionTypeLong9 = 34;
        long seqNo9 = 35;
        long primaryTerm9 = 36;
        long versionLong10 = 37;
        long versionTypeLong10 = 38;
        long seqNo10 = 39;
        long primaryTerm10 = 40;
        long versionLong11 = 41;
        long versionTypeLong11 = 42;
        long seqNo11 = 43;
        long primaryTerm11 = 44;
        long versionLong12 = 45;
        long versionTypeLong12
}