import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest43 {

    public static boolean debug = false;

    @Test
    public void test44() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest43.test44");
        org.graphstream.graph.Path path0 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path1 = new org.graphstream.graph.Path();
        boolean boolean2 = path0.equals(path1);
        org.graphstream.graph.Path path3 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path4 = new org.graphstream.graph.Path();
        boolean boolean5 = path3.equals(path4);
        boolean boolean6 = path0.equals(path4);
        org.graphstream.graph.Path path7 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path8 = new org.graphstream.graph.Path();
        boolean boolean9 = path7.equals(path8);
        boolean boolean10 = path0.equals(path8);
        org.graphstream.graph.Path path11 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path12 = new org.graphstream.graph.Path();
        boolean boolean13 = path11.equals(path12);
        org.graphstream.graph.Path path14 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path15 = new org.graphstream.graph.Path();
        boolean boolean16 = path14.equals(path15);
        org.graphstream.graph.Path path17 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path18 = new org.graphstream.graph.Path();
        boolean boolean19 = path17.equals(path18);
        boolean boolean20 = path14.equals(path18);
        org.graphstream.graph.Path path21 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path22 = new org.graphstream.graph.Path();
        boolean boolean23 = path21.equals(path22);
        org.graphstream.graph.Path path24 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path25 = new org.graphstream.graph.Path();
        boolean boolean26 = path24.equals(path25);
        boolean boolean27 = path21.equals(path25);
        boolean boolean28 = path14.equals(path21);
        boolean boolean29 = path12.equals(path14);
        org.graphstream.graph.Path path30 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path31 = new org.graphstream.graph.Path();
        boolean boolean32 = path30.equals(path31);
        org.graphstream.graph.Path path33 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path34 = new org.graphstream.graph.Path();
        boolean boolean35 = path33.equals(path34);
        boolean boolean36 = path30.equals(path34);
        org.graphstream.graph.Path path37 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path38 = new org.graphstream.graph.Path();
        boolean boolean39 = path37.equals(path38);
        org.graphstream.graph.Path path40 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path41 = new org.graphstream.graph.Path();
        boolean boolean42 = path40.equals(path41);
        boolean boolean43 = path37.equals(path41);
        boolean boolean44 = path30.equals(path37);
        org.graphstream.graph.Path path45 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path46 = new org.graphstream.graph.Path();
        boolean boolean47 = path45.equals(path46);
        org.graphstream.graph.Path path48 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path49 = new org.graphstream.graph.Path();
        boolean boolean50 = path48.equals(path49);
        org.graphstream.graph.Path path51 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path52 = new org.graphstream.graph.Path();
        boolean boolean53 = path51.equals(path52);
        boolean boolean54 = path48.equals(path52);
        org.graphstream.graph.Path path55 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path56 = new org.graphstream.graph.Path();
        boolean boolean57 = path55.equals(path56);
        org.graphstream.graph.Path path58 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path59 = new org.graphstream.graph.Path();
        boolean boolean60 = path58.equals(path59);
        boolean boolean61 = path55.equals(path59);
        boolean boolean62 = path48.equals(path55);
        boolean boolean63 = path46.equals(path48);
        org.graphstream.graph.Path path64 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path65 = new org.graphstream.graph.Path();
        boolean boolean66 = path64.equals(path65);
        boolean boolean67 = path48.equals(path64);
        org.graphstream.graph.Path path68 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path69 = new org.graphstream.graph.Path();
        boolean boolean70 = path68.equals(path69);
        org.graphstream.graph.Path path71 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path72 = new org.graphstream.graph.Path();
        boolean boolean73 = path71.equals(path72);
        boolean boolean74 = path68.equals(path72);
        org.graphstream.graph.Path path75 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path76 = new org.graphstream.graph.Path();
        boolean boolean77 = path75.equals(path76);
        org.graphstream.graph.Path path78 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path79 = new org.graphstream.graph.Path();
        boolean boolean80 = path78.equals(path79);
        org.graphstream.graph.Path path81 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path82 = new org.graphstream.graph.Path();
        boolean boolean83 = path81.equals(path82);
        boolean boolean84 = path78.equals(path82);
        org.graphstream.graph.Path path85 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path86 = new org.graphstream.graph.Path();
        boolean boolean87 = path85.equals(path86);
        org.graphstream.graph.Path path88 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path89 = new org.graphstream.graph.Path();
        boolean boolean90 = path88.equals(path89);
        boolean boolean91 = path85.equals(path89);
        boolean boolean92 = path78.equals(path85);
        boolean boolean93 = path76.equals(path85);
        boolean boolean94 = path68.equals(path76);
        boolean boolean95 = path64.equals(path68);
        boolean boolean96 = path37.equals(path68);
        boolean boolean97 = path12.equals(path68);
        boolean boolean98 = path8.equals(path68);
        org.junit.Assert.assertTrue("'" + boolean2 + "' != '" + true + "'", boolean2 == true);
        org.junit.Assert.assertTrue("'" + boolean5 + "' != '" + true + "'", boolean5 == true);
        org.junit.Assert.assertTrue("'" + boolean6 + "' != '" + true + "'", boolean6 == true);
        org.junit.Assert.assertTrue("'" + boolean9 + "' != '" + true + "'", boolean9 == true);
        org.junit.Assert.assertTrue("'" + boolean10 + "' != '" + true + "'", boolean10 == true);
        org.junit.Assert.assertTrue("'" + boolean13 + "' != '" + true + "'", boolean13 == true);
        org.junit.Assert.assertTrue("'" + boolean16 + "' != '" + true + "'", boolean16 == true);
        org.junit.Assert.assertTrue("'" + boolean19 + "' != '" + true + "'", boolean19 == true);
        org.junit.Assert.assertTrue("'" + boolean20 + "' != '" + true + "'", boolean20 == true);
        org.junit.Assert.assertTrue("'" + boolean23 + "' != '" + true + "'", boolean23 == true);
        org.junit.Assert.assertTrue("'" + boolean26 + "' != '" + true + "'", boolean26 == true);
        org.junit.Assert.assertTrue("'" + boolean27 + "' != '" + true + "'", boolean27 == true);
        org.junit.Assert.assertTrue("'" + boolean28 + "' != '" + true + "'", boolean28 == true);
        org.junit.Assert.assertTrue("'" + boolean29 + "' != '" + true + "'", boolean29 == true);
        org.junit.Assert.assertTrue("'" + boolean32 + "' != '" + true + "'", boolean32 == true);
        org.junit.Assert.assertTrue("'" + boolean35 + "' != '" + true + "'", boolean35 == true);
        org.junit.Assert.assertTrue("'" + boolean36 + "' != '" + true + "'", boolean36 == true);
        org.junit.Assert.assertTrue("'" + boolean39 + "' != '" + true + "'", boolean39 == true);
        org.junit.Assert.assertTrue("'" + boolean42 + "' != '" + true + "'", boolean42 == true);
        org.junit.Assert.assertTrue("'" + boolean43 + "' != '" + true + "'", boolean43 == true);
        org.junit.Assert.assertTrue("'" + boolean44 + "' != '" + true + "'", boolean44 == true);
        org.junit.Assert.assertTrue("'" + boolean47 + "' != '" + true + "'", boolean47 == true);
        org.junit.Assert.assertTrue("'" + boolean50 + "' != '" + true + "'", boolean50 == true);
        org.junit.Assert.assertTrue("'" + boolean53 + "' != '" + true + "'", boolean53 == true);
        org.junit.Assert.assertTrue("'" + boolean54 + "' != '" + true + "'", boolean54 == true);
        org.junit.Assert.assertTrue("'" + boolean57 + "' != '" + true + "'", boolean57 == true);
        org.junit.Assert.assertTrue("'" + boolean60 + "' != '" + true + "'", boolean60 == true);
        org.junit.Assert.assertTrue("'" + boolean61 + "' != '" + true + "'", boolean61 == true);
        org.junit.Assert.assertTrue("'" + boolean62 + "' != '" + true + "'", boolean62 == true);
        org.junit.Assert.assertTrue("'" + boolean63 + "' != '" + true + "'", boolean63 == true);
        org.junit.Assert.assertTrue("'" + boolean66 + "' != '" + true + "'", boolean66 == true);
        org.junit.Assert.assertTrue("'" + boolean67 + "' != '" + true + "'", boolean67 == true);
        org.junit.Assert.assertTrue("'" + boolean70 + "' != '" + true + "'", boolean70 == true);
        org.junit.Assert.assertTrue("'" + boolean73 + "' != '" + true + "'", boolean73 == true);
        org.junit.Assert.assertTrue("'" + boolean74 + "' != '" + true + "'", boolean74 == true);
        org.junit.Assert.assertTrue("'" + boolean77 + "' != '" + true + "'", boolean77 == true);
        org.junit.Assert.assertTrue("'" + boolean80 + "' != '" + true + "'", boolean80 == true);
        org.junit.Assert.assertTrue("'" + boolean83 + "' != '" + true + "'", boolean83 == true);
        org.junit.Assert.assertTrue("'" + boolean84 + "' != '" + true + "'", boolean84 == true);
        org.junit.Assert.assertTrue("'" + boolean87 + "' != '" + true + "'", boolean87 == true);
        org.junit.Assert.assertTrue("'" + boolean90 + "' != '" + true + "'", boolean90 == true);
        org.junit.Assert.assertTrue("'" + boolean91 + "' != '" + true + "'", boolean91 == true);
        org.junit.Assert.assertTrue("'" + boolean92 + "' != '" + true + "'", boolean92 == true);
        org.junit.Assert.assertTrue("'" + boolean93 + "' != '" + true + "'", boolean93 == true);
        org.junit.Assert.assertTrue("'" + boolean94 + "' != '" + true + "'", boolean94 == true);
        org.junit.Assert.assertTrue("'" + boolean95 + "' != '" + true + "'", boolean95 == true);
        org.junit.Assert.assertTrue("'" + boolean96 + "' != '" + true + "'", boolean96 == true);
        org.junit.Assert.assertTrue("'" + boolean97 + "' != '" + true + "'", boolean97 == true);
        org.junit.Assert.assertTrue("'" + boolean98 + "' != '" + true + "'", boolean98 == true);
    }
}

