import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest17 {

    public static boolean debug = false;

    @Test
    public void test18() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest17.test18");
        org.graphstream.graph.Path path0 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path1 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path2 = new org.graphstream.graph.Path();
        boolean boolean3 = path1.equals(path2);
        org.graphstream.graph.Path path4 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path5 = new org.graphstream.graph.Path();
        boolean boolean6 = path4.equals(path5);
        boolean boolean7 = path1.equals(path5);
        org.graphstream.graph.Path path8 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path9 = new org.graphstream.graph.Path();
        boolean boolean10 = path8.equals(path9);
        org.graphstream.graph.Path path11 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path12 = new org.graphstream.graph.Path();
        boolean boolean13 = path11.equals(path12);
        boolean boolean14 = path8.equals(path12);
        boolean boolean15 = path1.equals(path8);
        boolean boolean16 = path0.equals(path1);
        org.graphstream.graph.Path path17 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path18 = new org.graphstream.graph.Path();
        boolean boolean19 = path17.equals(path18);
        org.graphstream.graph.Path path20 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path21 = new org.graphstream.graph.Path();
        boolean boolean22 = path20.equals(path21);
        org.graphstream.graph.Path path23 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path24 = new org.graphstream.graph.Path();
        boolean boolean25 = path23.equals(path24);
        boolean boolean26 = path20.equals(path24);
        org.graphstream.graph.Path path27 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path28 = new org.graphstream.graph.Path();
        boolean boolean29 = path27.equals(path28);
        org.graphstream.graph.Path path30 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path31 = new org.graphstream.graph.Path();
        boolean boolean32 = path30.equals(path31);
        boolean boolean33 = path27.equals(path31);
        boolean boolean34 = path20.equals(path27);
        boolean boolean35 = path18.equals(path20);
        org.graphstream.graph.Path path36 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path37 = new org.graphstream.graph.Path();
        boolean boolean38 = path36.equals(path37);
        boolean boolean39 = path20.equals(path36);
        org.graphstream.graph.Path path40 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path41 = new org.graphstream.graph.Path();
        boolean boolean42 = path40.equals(path41);
        org.graphstream.graph.Path path43 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path44 = new org.graphstream.graph.Path();
        boolean boolean45 = path43.equals(path44);
        boolean boolean46 = path40.equals(path44);
        org.graphstream.graph.Path path47 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path48 = new org.graphstream.graph.Path();
        boolean boolean49 = path47.equals(path48);
        org.graphstream.graph.Path path50 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path51 = new org.graphstream.graph.Path();
        boolean boolean52 = path50.equals(path51);
        org.graphstream.graph.Path path53 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path54 = new org.graphstream.graph.Path();
        boolean boolean55 = path53.equals(path54);
        boolean boolean56 = path50.equals(path54);
        org.graphstream.graph.Path path57 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path58 = new org.graphstream.graph.Path();
        boolean boolean59 = path57.equals(path58);
        org.graphstream.graph.Path path60 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path61 = new org.graphstream.graph.Path();
        boolean boolean62 = path60.equals(path61);
        boolean boolean63 = path57.equals(path61);
        boolean boolean64 = path50.equals(path57);
        boolean boolean65 = path48.equals(path57);
        boolean boolean66 = path40.equals(path48);
        boolean boolean67 = path36.equals(path40);
        boolean boolean68 = path0.equals(path36);
        org.graphstream.graph.Path path69 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path70 = new org.graphstream.graph.Path();
        boolean boolean71 = path69.equals(path70);
        org.graphstream.graph.Path path72 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path73 = new org.graphstream.graph.Path();
        boolean boolean74 = path72.equals(path73);
        boolean boolean75 = path69.equals(path73);
        org.graphstream.graph.Path path76 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path77 = new org.graphstream.graph.Path();
        boolean boolean78 = path76.equals(path77);
        org.graphstream.graph.Path path79 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path80 = new org.graphstream.graph.Path();
        boolean boolean81 = path79.equals(path80);
        boolean boolean82 = path76.equals(path80);
        org.graphstream.graph.Path path83 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path84 = new org.graphstream.graph.Path();
        boolean boolean85 = path83.equals(path84);
        org.graphstream.graph.Path path86 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path87 = new org.graphstream.graph.Path();
        boolean boolean88 = path86.equals(path87);
        boolean boolean89 = path83.equals(path87);
        boolean boolean90 = path76.equals(path83);
        boolean boolean91 = path69.equals(path83);
        boolean boolean92 = path0.equals(path69);
        org.junit.Assert.assertTrue("'" + boolean3 + "' != '" + true + "'", boolean3 == true);
        org.junit.Assert.assertTrue("'" + boolean6 + "' != '" + true + "'", boolean6 == true);
        org.junit.Assert.assertTrue("'" + boolean7 + "' != '" + true + "'", boolean7 == true);
        org.junit.Assert.assertTrue("'" + boolean10 + "' != '" + true + "'", boolean10 == true);
        org.junit.Assert.assertTrue("'" + boolean13 + "' != '" + true + "'", boolean13 == true);
        org.junit.Assert.assertTrue("'" + boolean14 + "' != '" + true + "'", boolean14 == true);
        org.junit.Assert.assertTrue("'" + boolean15 + "' != '" + true + "'", boolean15 == true);
        org.junit.Assert.assertTrue("'" + boolean16 + "' != '" + true + "'", boolean16 == true);
        org.junit.Assert.assertTrue("'" + boolean19 + "' != '" + true + "'", boolean19 == true);
        org.junit.Assert.assertTrue("'" + boolean22 + "' != '" + true + "'", boolean22 == true);
        org.junit.Assert.assertTrue("'" + boolean25 + "' != '" + true + "'", boolean25 == true);
        org.junit.Assert.assertTrue("'" + boolean26 + "' != '" + true + "'", boolean26 == true);
        org.junit.Assert.assertTrue("'" + boolean29 + "' != '" + true + "'", boolean29 == true);
        org.junit.Assert.assertTrue("'" + boolean32 + "' != '" + true + "'", boolean32 == true);
        org.junit.Assert.assertTrue("'" + boolean33 + "' != '" + true + "'", boolean33 == true);
        org.junit.Assert.assertTrue("'" + boolean34 + "' != '" + true + "'", boolean34 == true);
        org.junit.Assert.assertTrue("'" + boolean35 + "' != '" + true + "'", boolean35 == true);
        org.junit.Assert.assertTrue("'" + boolean38 + "' != '" + true + "'", boolean38 == true);
        org.junit.Assert.assertTrue("'" + boolean39 + "' != '" + true + "'", boolean39 == true);
        org.junit.Assert.assertTrue("'" + boolean42 + "' != '" + true + "'", boolean42 == true);
        org.junit.Assert.assertTrue("'" + boolean45 + "' != '" + true + "'", boolean45 == true);
        org.junit.Assert.assertTrue("'" + boolean46 + "' != '" + true + "'", boolean46 == true);
        org.junit.Assert.assertTrue("'" + boolean49 + "' != '" + true + "'", boolean49 == true);
        org.junit.Assert.assertTrue("'" + boolean52 + "' != '" + true + "'", boolean52 == true);
        org.junit.Assert.assertTrue("'" + boolean55 + "' != '" + true + "'", boolean55 == true);
        org.junit.Assert.assertTrue("'" + boolean56 + "' != '" + true + "'", boolean56 == true);
        org.junit.Assert.assertTrue("'" + boolean59 + "' != '" + true + "'", boolean59 == true);
        org.junit.Assert.assertTrue("'" + boolean62 + "' != '" + true + "'", boolean62 == true);
        org.junit.Assert.assertTrue("'" + boolean63 + "' != '" + true + "'", boolean63 == true);
        org.junit.Assert.assertTrue("'" + boolean64 + "' != '" + true + "'", boolean64 == true);
        org.junit.Assert.assertTrue("'" + boolean65 + "' != '" + true + "'", boolean65 == true);
        org.junit.Assert.assertTrue("'" + boolean66 + "' != '" + true + "'", boolean66 == true);
        org.junit.Assert.assertTrue("'" + boolean67 + "' != '" + true + "'", boolean67 == true);
        org.junit.Assert.assertTrue("'" + boolean68 + "' != '" + true + "'", boolean68 == true);
        org.junit.Assert.assertTrue("'" + boolean71 + "' != '" + true + "'", boolean71 == true);
        org.junit.Assert.assertTrue("'" + boolean74 + "' != '" + true + "'", boolean74 == true);
        org.junit.Assert.assertTrue("'" + boolean75 + "' != '" + true + "'", boolean75 == true);
        org.junit.Assert.assertTrue("'" + boolean78 + "' != '" + true + "'", boolean78 == true);
        org.junit.Assert.assertTrue("'" + boolean81 + "' != '" + true + "'", boolean81 == true);
        org.junit.Assert.assertTrue("'" + boolean82 + "' != '" + true + "'", boolean82 == true);
        org.junit.Assert.assertTrue("'" + boolean85 + "' != '" + true + "'", boolean85 == true);
        org.junit.Assert.assertTrue("'" + boolean88 + "' != '" + true + "'", boolean88 == true);
        org.junit.Assert.assertTrue("'" + boolean89 + "' != '" + true + "'", boolean89 == true);
        org.junit.Assert.assertTrue("'" + boolean90 + "' != '" + true + "'", boolean90 == true);
        org.junit.Assert.assertTrue("'" + boolean91 + "' != '" + true + "'", boolean91 == true);
        org.junit.Assert.assertTrue("'" + boolean92 + "' != '" + true + "'", boolean92 == true);
    }
}

