import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest7 {

    public static boolean debug = false;

    @Test
    public void test08() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest7.test08");
        org.graphstream.graph.Path path0 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path1 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path2 = new org.graphstream.graph.Path();
        boolean boolean3 = path1.equals(path2);
        org.graphstream.graph.Path path4 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path5 = new org.graphstream.graph.Path();
        boolean boolean6 = path4.equals(path5);
        org.graphstream.graph.Path path7 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path8 = new org.graphstream.graph.Path();
        boolean boolean9 = path7.equals(path8);
        boolean boolean10 = path4.equals(path8);
        org.graphstream.graph.Path path11 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path12 = new org.graphstream.graph.Path();
        boolean boolean13 = path11.equals(path12);
        org.graphstream.graph.Path path14 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path15 = new org.graphstream.graph.Path();
        boolean boolean16 = path14.equals(path15);
        boolean boolean17 = path11.equals(path15);
        boolean boolean18 = path4.equals(path11);
        boolean boolean19 = path2.equals(path11);
        boolean boolean20 = path0.equals(path2);
        org.graphstream.graph.Path path21 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path22 = new org.graphstream.graph.Path();
        boolean boolean23 = path21.equals(path22);
        org.graphstream.graph.Path path24 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path25 = new org.graphstream.graph.Path();
        boolean boolean26 = path24.equals(path25);
        boolean boolean27 = path21.equals(path25);
        org.graphstream.graph.Path path28 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path29 = new org.graphstream.graph.Path();
        boolean boolean30 = path28.equals(path29);
        org.graphstream.graph.Path path31 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path32 = new org.graphstream.graph.Path();
        boolean boolean33 = path31.equals(path32);
        boolean boolean34 = path28.equals(path32);
        boolean boolean35 = path25.equals(path32);
        boolean boolean36 = path0.equals(path25);
        org.graphstream.graph.Path path37 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path38 = new org.graphstream.graph.Path();
        boolean boolean39 = path37.equals(path38);
        org.graphstream.graph.Path path40 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path41 = new org.graphstream.graph.Path();
        boolean boolean42 = path40.equals(path41);
        org.graphstream.graph.Path path43 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path44 = new org.graphstream.graph.Path();
        boolean boolean45 = path43.equals(path44);
        boolean boolean46 = path40.equals(path44);
        org.graphstream.graph.Path path47 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path48 = new org.graphstream.graph.Path();
        boolean boolean49 = path47.equals(path48);
        org.graphstream.graph.Path path50 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path51 = new org.graphstream.graph.Path();
        boolean boolean52 = path50.equals(path51);
        boolean boolean53 = path47.equals(path51);
        boolean boolean54 = path40.equals(path47);
        boolean boolean55 = path38.equals(path40);
        org.graphstream.graph.Path path56 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path57 = new org.graphstream.graph.Path();
        boolean boolean58 = path56.equals(path57);
        org.graphstream.graph.Path path59 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path60 = new org.graphstream.graph.Path();
        boolean boolean61 = path59.equals(path60);
        boolean boolean62 = path56.equals(path60);
        org.graphstream.graph.Path path63 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path64 = new org.graphstream.graph.Path();
        boolean boolean65 = path63.equals(path64);
        org.graphstream.graph.Path path66 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path67 = new org.graphstream.graph.Path();
        boolean boolean68 = path66.equals(path67);
        boolean boolean69 = path63.equals(path67);
        boolean boolean70 = path60.equals(path67);
        boolean boolean71 = path38.equals(path67);
        org.graphstream.graph.Path path72 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path73 = new org.graphstream.graph.Path();
        boolean boolean74 = path72.equals(path73);
        org.graphstream.graph.Path path75 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path76 = new org.graphstream.graph.Path();
        boolean boolean77 = path75.equals(path76);
        boolean boolean78 = path72.equals(path76);
        org.graphstream.graph.Path path79 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path80 = new org.graphstream.graph.Path();
        boolean boolean81 = path79.equals(path80);
        boolean boolean82 = path72.equals(path79);
        boolean boolean83 = path67.equals(path72);
        boolean boolean84 = path0.equals(path72);
        org.junit.Assert.assertTrue("'" + boolean3 + "' != '" + true + "'", boolean3 == true);
        org.junit.Assert.assertTrue("'" + boolean6 + "' != '" + true + "'", boolean6 == true);
        org.junit.Assert.assertTrue("'" + boolean9 + "' != '" + true + "'", boolean9 == true);
        org.junit.Assert.assertTrue("'" + boolean10 + "' != '" + true + "'", boolean10 == true);
        org.junit.Assert.assertTrue("'" + boolean13 + "' != '" + true + "'", boolean13 == true);
        org.junit.Assert.assertTrue("'" + boolean16 + "' != '" + true + "'", boolean16 == true);
        org.junit.Assert.assertTrue("'" + boolean17 + "' != '" + true + "'", boolean17 == true);
        org.junit.Assert.assertTrue("'" + boolean18 + "' != '" + true + "'", boolean18 == true);
        org.junit.Assert.assertTrue("'" + boolean19 + "' != '" + true + "'", boolean19 == true);
        org.junit.Assert.assertTrue("'" + boolean20 + "' != '" + true + "'", boolean20 == true);
        org.junit.Assert.assertTrue("'" + boolean23 + "' != '" + true + "'", boolean23 == true);
        org.junit.Assert.assertTrue("'" + boolean26 + "' != '" + true + "'", boolean26 == true);
        org.junit.Assert.assertTrue("'" + boolean27 + "' != '" + true + "'", boolean27 == true);
        org.junit.Assert.assertTrue("'" + boolean30 + "' != '" + true + "'", boolean30 == true);
        org.junit.Assert.assertTrue("'" + boolean33 + "' != '" + true + "'", boolean33 == true);
        org.junit.Assert.assertTrue("'" + boolean34 + "' != '" + true + "'", boolean34 == true);
        org.junit.Assert.assertTrue("'" + boolean35 + "' != '" + true + "'", boolean35 == true);
        org.junit.Assert.assertTrue("'" + boolean36 + "' != '" + true + "'", boolean36 == true);
        org.junit.Assert.assertTrue("'" + boolean39 + "' != '" + true + "'", boolean39 == true);
        org.junit.Assert.assertTrue("'" + boolean42 + "' != '" + true + "'", boolean42 == true);
        org.junit.Assert.assertTrue("'" + boolean45 + "' != '" + true + "'", boolean45 == true);
        org.junit.Assert.assertTrue("'" + boolean46 + "' != '" + true + "'", boolean46 == true);
        org.junit.Assert.assertTrue("'" + boolean49 + "' != '" + true + "'", boolean49 == true);
        org.junit.Assert.assertTrue("'" + boolean52 + "' != '" + true + "'", boolean52 == true);
        org.junit.Assert.assertTrue("'" + boolean53 + "' != '" + true + "'", boolean53 == true);
        org.junit.Assert.assertTrue("'" + boolean54 + "' != '" + true + "'", boolean54 == true);
        org.junit.Assert.assertTrue("'" + boolean55 + "' != '" + true + "'", boolean55 == true);
        org.junit.Assert.assertTrue("'" + boolean58 + "' != '" + true + "'", boolean58 == true);
        org.junit.Assert.assertTrue("'" + boolean61 + "' != '" + true + "'", boolean61 == true);
        org.junit.Assert.assertTrue("'" + boolean62 + "' != '" + true + "'", boolean62 == true);
        org.junit.Assert.assertTrue("'" + boolean65 + "' != '" + true + "'", boolean65 == true);
        org.junit.Assert.assertTrue("'" + boolean68 + "' != '" + true + "'", boolean68 == true);
        org.junit.Assert.assertTrue("'" + boolean69 + "' != '" + true + "'", boolean69 == true);
        org.junit.Assert.assertTrue("'" + boolean70 + "' != '" + true + "'", boolean70 == true);
        org.junit.Assert.assertTrue("'" + boolean71 + "' != '" + true + "'", boolean71 == true);
        org.junit.Assert.assertTrue("'" + boolean74 + "' != '" + true + "'", boolean74 == true);
        org.junit.Assert.assertTrue("'" + boolean77 + "' != '" + true + "'", boolean77 == true);
        org.junit.Assert.assertTrue("'" + boolean78 + "' != '" + true + "'", boolean78 == true);
        org.junit.Assert.assertTrue("'" + boolean81 + "' != '" + true + "'", boolean81 == true);
        org.junit.Assert.assertTrue("'" + boolean82 + "' != '" + true + "'", boolean82 == true);
        org.junit.Assert.assertTrue("'" + boolean83 + "' != '" + true + "'", boolean83 == true);
        org.junit.Assert.assertTrue("'" + boolean84 + "' != '" + true + "'", boolean84 == true);
    }
}

