import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest3 {

    public static boolean debug = false;

    @Test
    public void test04() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest3.test04");
        org.graphstream.graph.Path path0 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path1 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path2 = new org.graphstream.graph.Path();
        boolean boolean3 = path1.equals(path2);
        org.graphstream.graph.Path path4 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path5 = new org.graphstream.graph.Path();
        boolean boolean6 = path4.equals(path5);
        boolean boolean7 = path1.equals(path5);
        boolean boolean8 = path0.equals(path1);
        org.graphstream.graph.Path path9 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path10 = new org.graphstream.graph.Path();
        boolean boolean11 = path9.equals(path10);
        org.graphstream.graph.Path path12 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path13 = new org.graphstream.graph.Path();
        boolean boolean14 = path12.equals(path13);
        org.graphstream.graph.Path path15 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path16 = new org.graphstream.graph.Path();
        boolean boolean17 = path15.equals(path16);
        boolean boolean18 = path12.equals(path16);
        org.graphstream.graph.Path path19 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path20 = new org.graphstream.graph.Path();
        boolean boolean21 = path19.equals(path20);
        org.graphstream.graph.Path path22 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path23 = new org.graphstream.graph.Path();
        boolean boolean24 = path22.equals(path23);
        boolean boolean25 = path19.equals(path23);
        boolean boolean26 = path12.equals(path19);
        boolean boolean27 = path10.equals(path12);
        org.graphstream.graph.Path path28 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path29 = new org.graphstream.graph.Path();
        boolean boolean30 = path28.equals(path29);
        org.graphstream.graph.Path path31 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path32 = new org.graphstream.graph.Path();
        boolean boolean33 = path31.equals(path32);
        boolean boolean34 = path28.equals(path32);
        org.graphstream.graph.Path path35 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path36 = new org.graphstream.graph.Path();
        boolean boolean37 = path35.equals(path36);
        org.graphstream.graph.Path path38 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path39 = new org.graphstream.graph.Path();
        boolean boolean40 = path38.equals(path39);
        boolean boolean41 = path35.equals(path39);
        boolean boolean42 = path32.equals(path39);
        boolean boolean43 = path10.equals(path39);
        boolean boolean44 = path0.equals(path39);
        org.graphstream.graph.Path path45 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path46 = new org.graphstream.graph.Path();
        boolean boolean47 = path45.equals(path46);
        org.graphstream.graph.Path path48 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path49 = new org.graphstream.graph.Path();
        boolean boolean50 = path48.equals(path49);
        org.graphstream.graph.Path path51 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path52 = new org.graphstream.graph.Path();
        boolean boolean53 = path51.equals(path52);
        boolean boolean54 = path48.equals(path52);
        org.graphstream.graph.Path path55 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path56 = new org.graphstream.graph.Path();
        boolean boolean57 = path55.equals(path56);
        org.graphstream.graph.Path path58 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path59 = new org.graphstream.graph.Path();
        boolean boolean60 = path58.equals(path59);
        boolean boolean61 = path55.equals(path59);
        boolean boolean62 = path48.equals(path55);
        boolean boolean63 = path46.equals(path48);
        org.graphstream.graph.Path path64 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path65 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path66 = new org.graphstream.graph.Path();
        boolean boolean67 = path65.equals(path66);
        org.graphstream.graph.Path path68 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path69 = new org.graphstream.graph.Path();
        boolean boolean70 = path68.equals(path69);
        org.graphstream.graph.Path path71 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path72 = new org.graphstream.graph.Path();
        boolean boolean73 = path71.equals(path72);
        boolean boolean74 = path68.equals(path72);
        org.graphstream.graph.Path path75 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path76 = new org.graphstream.graph.Path();
        boolean boolean77 = path75.equals(path76);
        org.graphstream.graph.Path path78 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path79 = new org.graphstream.graph.Path();
        boolean boolean80 = path78.equals(path79);
        boolean boolean81 = path75.equals(path79);
        boolean boolean82 = path68.equals(path75);
        boolean boolean83 = path66.equals(path75);
        boolean boolean84 = path64.equals(path66);
        org.graphstream.graph.Path path85 = new org.graphstream.graph.Path();
        boolean boolean86 = path66.equals(path85);
        boolean boolean87 = path48.equals(path66);
        boolean boolean88 = path0.equals(path66);
        org.junit.Assert.assertTrue("'" + boolean3 + "' != '" + true + "'", boolean3 == true);
        org.junit.Assert.assertTrue("'" + boolean6 + "' != '" + true + "'", boolean6 == true);
        org.junit.Assert.assertTrue("'" + boolean7 + "' != '" + true + "'", boolean7 == true);
        org.junit.Assert.assertTrue("'" + boolean8 + "' != '" + true + "'", boolean8 == true);
        org.junit.Assert.assertTrue("'" + boolean11 + "' != '" + true + "'", boolean11 == true);
        org.junit.Assert.assertTrue("'" + boolean14 + "' != '" + true + "'", boolean14 == true);
        org.junit.Assert.assertTrue("'" + boolean17 + "' != '" + true + "'", boolean17 == true);
        org.junit.Assert.assertTrue("'" + boolean18 + "' != '" + true + "'", boolean18 == true);
        org.junit.Assert.assertTrue("'" + boolean21 + "' != '" + true + "'", boolean21 == true);
        org.junit.Assert.assertTrue("'" + boolean24 + "' != '" + true + "'", boolean24 == true);
        org.junit.Assert.assertTrue("'" + boolean25 + "' != '" + true + "'", boolean25 == true);
        org.junit.Assert.assertTrue("'" + boolean26 + "' != '" + true + "'", boolean26 == true);
        org.junit.Assert.assertTrue("'" + boolean27 + "' != '" + true + "'", boolean27 == true);
        org.junit.Assert.assertTrue("'" + boolean30 + "' != '" + true + "'", boolean30 == true);
        org.junit.Assert.assertTrue("'" + boolean33 + "' != '" + true + "'", boolean33 == true);
        org.junit.Assert.assertTrue("'" + boolean34 + "' != '" + true + "'", boolean34 == true);
        org.junit.Assert.assertTrue("'" + boolean37 + "' != '" + true + "'", boolean37 == true);
        org.junit.Assert.assertTrue("'" + boolean40 + "' != '" + true + "'", boolean40 == true);
        org.junit.Assert.assertTrue("'" + boolean41 + "' != '" + true + "'", boolean41 == true);
        org.junit.Assert.assertTrue("'" + boolean42 + "' != '" + true + "'", boolean42 == true);
        org.junit.Assert.assertTrue("'" + boolean43 + "' != '" + true + "'", boolean43 == true);
        org.junit.Assert.assertTrue("'" + boolean44 + "' != '" + true + "'", boolean44 == true);
        org.junit.Assert.assertTrue("'" + boolean47 + "' != '" + true + "'", boolean47 == true);
        org.junit.Assert.assertTrue("'" + boolean50 + "' != '" + true + "'", boolean50 == true);
        org.junit.Assert.assertTrue("'" + boolean53 + "' != '" + true + "'", boolean53 == true);
        org.junit.Assert.assertTrue("'" + boolean54 + "' != '" + true + "'", boolean54 == true);
        org.junit.Assert.assertTrue("'" + boolean57 + "' != '" + true + "'", boolean57 == true);
        org.junit.Assert.assertTrue("'" + boolean60 + "' != '" + true + "'", boolean60 == true);
        org.junit.Assert.assertTrue("'" + boolean61 + "' != '" + true + "'", boolean61 == true);
        org.junit.Assert.assertTrue("'" + boolean62 + "' != '" + true + "'", boolean62 == true);
        org.junit.Assert.assertTrue("'" + boolean63 + "' != '" + true + "'", boolean63 == true);
        org.junit.Assert.assertTrue("'" + boolean67 + "' != '" + true + "'", boolean67 == true);
        org.junit.Assert.assertTrue("'" + boolean70 + "' != '" + true + "'", boolean70 == true);
        org.junit.Assert.assertTrue("'" + boolean73 + "' != '" + true + "'", boolean73 == true);
        org.junit.Assert.assertTrue("'" + boolean74 + "' != '" + true + "'", boolean74 == true);
        org.junit.Assert.assertTrue("'" + boolean77 + "' != '" + true + "'", boolean77 == true);
        org.junit.Assert.assertTrue("'" + boolean80 + "' != '" + true + "'", boolean80 == true);
        org.junit.Assert.assertTrue("'" + boolean81 + "' != '" + true + "'", boolean81 == true);
        org.junit.Assert.assertTrue("'" + boolean82 + "' != '" + true + "'", boolean82 == true);
        org.junit.Assert.assertTrue("'" + boolean83 + "' != '" + true + "'", boolean83 == true);
        org.junit.Assert.assertTrue("'" + boolean84 + "' != '" + true + "'", boolean84 == true);
        org.junit.Assert.assertTrue("'" + boolean86 + "' != '" + true + "'", boolean86 == true);
        org.junit.Assert.assertTrue("'" + boolean87 + "' != '" + true + "'", boolean87 == true);
        org.junit.Assert.assertTrue("'" + boolean88 + "' != '" + true + "'", boolean88 == true);
    }
}

