import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest40 {

    public static boolean debug = false;

    @Test
    public void test41() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest40.test41");
        org.graphstream.graph.Path path0 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path1 = new org.graphstream.graph.Path();
        boolean boolean2 = path0.equals(path1);
        org.graphstream.graph.Path path3 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path4 = new org.graphstream.graph.Path();
        boolean boolean5 = path3.equals(path4);
        boolean boolean6 = path0.equals(path4);
        org.graphstream.graph.Path path7 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path8 = new org.graphstream.graph.Path();
        boolean boolean9 = path7.equals(path8);
        boolean boolean10 = path0.equals(path7);
        org.graphstream.graph.Path path11 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path12 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path13 = new org.graphstream.graph.Path();
        boolean boolean14 = path12.equals(path13);
        org.graphstream.graph.Path path15 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path16 = new org.graphstream.graph.Path();
        boolean boolean17 = path15.equals(path16);
        org.graphstream.graph.Path path18 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path19 = new org.graphstream.graph.Path();
        boolean boolean20 = path18.equals(path19);
        boolean boolean21 = path15.equals(path19);
        org.graphstream.graph.Path path22 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path23 = new org.graphstream.graph.Path();
        boolean boolean24 = path22.equals(path23);
        org.graphstream.graph.Path path25 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path26 = new org.graphstream.graph.Path();
        boolean boolean27 = path25.equals(path26);
        boolean boolean28 = path22.equals(path26);
        boolean boolean29 = path15.equals(path22);
        boolean boolean30 = path13.equals(path22);
        boolean boolean31 = path11.equals(path13);
        org.graphstream.graph.Path path32 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path33 = new org.graphstream.graph.Path();
        boolean boolean34 = path32.equals(path33);
        org.graphstream.graph.Path path35 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path36 = new org.graphstream.graph.Path();
        boolean boolean37 = path35.equals(path36);
        boolean boolean38 = path32.equals(path36);
        org.graphstream.graph.Path path39 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path40 = new org.graphstream.graph.Path();
        boolean boolean41 = path39.equals(path40);
        org.graphstream.graph.Path path42 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path43 = new org.graphstream.graph.Path();
        boolean boolean44 = path42.equals(path43);
        boolean boolean45 = path39.equals(path43);
        boolean boolean46 = path36.equals(path43);
        boolean boolean47 = path11.equals(path36);
        boolean boolean48 = path0.equals(path36);
        org.graphstream.graph.Path path49 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path50 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path51 = new org.graphstream.graph.Path();
        boolean boolean52 = path50.equals(path51);
        org.graphstream.graph.Path path53 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path54 = new org.graphstream.graph.Path();
        boolean boolean55 = path53.equals(path54);
        org.graphstream.graph.Path path56 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path57 = new org.graphstream.graph.Path();
        boolean boolean58 = path56.equals(path57);
        boolean boolean59 = path53.equals(path57);
        org.graphstream.graph.Path path60 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path61 = new org.graphstream.graph.Path();
        boolean boolean62 = path60.equals(path61);
        org.graphstream.graph.Path path63 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path64 = new org.graphstream.graph.Path();
        boolean boolean65 = path63.equals(path64);
        boolean boolean66 = path60.equals(path64);
        boolean boolean67 = path53.equals(path60);
        boolean boolean68 = path51.equals(path60);
        boolean boolean69 = path49.equals(path51);
        boolean boolean70 = path0.equals(path51);
        org.junit.Assert.assertTrue("'" + boolean2 + "' != '" + true + "'", boolean2 == true);
        org.junit.Assert.assertTrue("'" + boolean5 + "' != '" + true + "'", boolean5 == true);
        org.junit.Assert.assertTrue("'" + boolean6 + "' != '" + true + "'", boolean6 == true);
        org.junit.Assert.assertTrue("'" + boolean9 + "' != '" + true + "'", boolean9 == true);
        org.junit.Assert.assertTrue("'" + boolean10 + "' != '" + true + "'", boolean10 == true);
        org.junit.Assert.assertTrue("'" + boolean14 + "' != '" + true + "'", boolean14 == true);
        org.junit.Assert.assertTrue("'" + boolean17 + "' != '" + true + "'", boolean17 == true);
        org.junit.Assert.assertTrue("'" + boolean20 + "' != '" + true + "'", boolean20 == true);
        org.junit.Assert.assertTrue("'" + boolean21 + "' != '" + true + "'", boolean21 == true);
        org.junit.Assert.assertTrue("'" + boolean24 + "' != '" + true + "'", boolean24 == true);
        org.junit.Assert.assertTrue("'" + boolean27 + "' != '" + true + "'", boolean27 == true);
        org.junit.Assert.assertTrue("'" + boolean28 + "' != '" + true + "'", boolean28 == true);
        org.junit.Assert.assertTrue("'" + boolean29 + "' != '" + true + "'", boolean29 == true);
        org.junit.Assert.assertTrue("'" + boolean30 + "' != '" + true + "'", boolean30 == true);
        org.junit.Assert.assertTrue("'" + boolean31 + "' != '" + true + "'", boolean31 == true);
        org.junit.Assert.assertTrue("'" + boolean34 + "' != '" + true + "'", boolean34 == true);
        org.junit.Assert.assertTrue("'" + boolean37 + "' != '" + true + "'", boolean37 == true);
        org.junit.Assert.assertTrue("'" + boolean38 + "' != '" + true + "'", boolean38 == true);
        org.junit.Assert.assertTrue("'" + boolean41 + "' != '" + true + "'", boolean41 == true);
        org.junit.Assert.assertTrue("'" + boolean44 + "' != '" + true + "'", boolean44 == true);
        org.junit.Assert.assertTrue("'" + boolean45 + "' != '" + true + "'", boolean45 == true);
        org.junit.Assert.assertTrue("'" + boolean46 + "' != '" + true + "'", boolean46 == true);
        org.junit.Assert.assertTrue("'" + boolean47 + "' != '" + true + "'", boolean47 == true);
        org.junit.Assert.assertTrue("'" + boolean48 + "' != '" + true + "'", boolean48 == true);
        org.junit.Assert.assertTrue("'" + boolean52 + "' != '" + true + "'", boolean52 == true);
        org.junit.Assert.assertTrue("'" + boolean55 + "' != '" + true + "'", boolean55 == true);
        org.junit.Assert.assertTrue("'" + boolean58 + "' != '" + true + "'", boolean58 == true);
        org.junit.Assert.assertTrue("'" + boolean59 + "' != '" + true + "'", boolean59 == true);
        org.junit.Assert.assertTrue("'" + boolean62 + "' != '" + true + "'", boolean62 == true);
        org.junit.Assert.assertTrue("'" + boolean65 + "' != '" + true + "'", boolean65 == true);
        org.junit.Assert.assertTrue("'" + boolean66 + "' != '" + true + "'", boolean66 == true);
        org.junit.Assert.assertTrue("'" + boolean67 + "' != '" + true + "'", boolean67 == true);
        org.junit.Assert.assertTrue("'" + boolean68 + "' != '" + true + "'", boolean68 == true);
        org.junit.Assert.assertTrue("'" + boolean69 + "' != '" + true + "'", boolean69 == true);
        org.junit.Assert.assertTrue("'" + boolean70 + "' != '" + true + "'", boolean70 == true);
    }
}

