import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest30 {

    public static boolean debug = false;

    @Test
    public void test31() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest30.test31");
        org.graphstream.graph.Path path0 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path1 = new org.graphstream.graph.Path();
        boolean boolean2 = path0.equals(path1);
        org.graphstream.graph.Path path3 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path4 = new org.graphstream.graph.Path();
        boolean boolean5 = path3.equals(path4);
        org.graphstream.graph.Path path6 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path7 = new org.graphstream.graph.Path();
        boolean boolean8 = path6.equals(path7);
        boolean boolean9 = path3.equals(path7);
        boolean boolean10 = path1.equals(path3);
        org.graphstream.graph.Path path11 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path12 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path13 = new org.graphstream.graph.Path();
        boolean boolean14 = path12.equals(path13);
        org.graphstream.graph.Path path15 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path16 = new org.graphstream.graph.Path();
        boolean boolean17 = path15.equals(path16);
        org.graphstream.graph.Path path18 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path19 = new org.graphstream.graph.Path();
        boolean boolean20 = path18.equals(path19);
        boolean boolean21 = path15.equals(path19);
        org.graphstream.graph.Path path22 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path23 = new org.graphstream.graph.Path();
        boolean boolean24 = path22.equals(path23);
        org.graphstream.graph.Path path25 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path26 = new org.graphstream.graph.Path();
        boolean boolean27 = path25.equals(path26);
        boolean boolean28 = path22.equals(path26);
        boolean boolean29 = path15.equals(path22);
        boolean boolean30 = path13.equals(path22);
        boolean boolean31 = path11.equals(path13);
        org.graphstream.graph.Path path32 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path33 = new org.graphstream.graph.Path();
        boolean boolean34 = path32.equals(path33);
        org.graphstream.graph.Path path35 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path36 = new org.graphstream.graph.Path();
        boolean boolean37 = path35.equals(path36);
        boolean boolean38 = path32.equals(path36);
        org.graphstream.graph.Path path39 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path40 = new org.graphstream.graph.Path();
        boolean boolean41 = path39.equals(path40);
        org.graphstream.graph.Path path42 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path43 = new org.graphstream.graph.Path();
        boolean boolean44 = path42.equals(path43);
        boolean boolean45 = path39.equals(path43);
        boolean boolean46 = path36.equals(path43);
        boolean boolean47 = path11.equals(path36);
        org.graphstream.graph.Path path48 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path49 = new org.graphstream.graph.Path();
        boolean boolean50 = path48.equals(path49);
        boolean boolean51 = path11.equals(path49);
        org.graphstream.graph.Path path52 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path53 = new org.graphstream.graph.Path();
        boolean boolean54 = path52.equals(path53);
        org.graphstream.graph.Path path55 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path56 = new org.graphstream.graph.Path();
        boolean boolean57 = path55.equals(path56);
        org.graphstream.graph.Path path58 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path59 = new org.graphstream.graph.Path();
        boolean boolean60 = path58.equals(path59);
        boolean boolean61 = path55.equals(path59);
        org.graphstream.graph.Path path62 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path63 = new org.graphstream.graph.Path();
        boolean boolean64 = path62.equals(path63);
        org.graphstream.graph.Path path65 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path66 = new org.graphstream.graph.Path();
        boolean boolean67 = path65.equals(path66);
        boolean boolean68 = path62.equals(path66);
        boolean boolean69 = path55.equals(path62);
        boolean boolean70 = path53.equals(path62);
        org.graphstream.graph.Path path71 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path72 = new org.graphstream.graph.Path();
        boolean boolean73 = path71.equals(path72);
        org.graphstream.graph.Path path74 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path75 = new org.graphstream.graph.Path();
        boolean boolean76 = path74.equals(path75);
        org.graphstream.graph.Path path77 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path78 = new org.graphstream.graph.Path();
        boolean boolean79 = path77.equals(path78);
        boolean boolean80 = path74.equals(path78);
        org.graphstream.graph.Path path81 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path82 = new org.graphstream.graph.Path();
        boolean boolean83 = path81.equals(path82);
        org.graphstream.graph.Path path84 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path85 = new org.graphstream.graph.Path();
        boolean boolean86 = path84.equals(path85);
        boolean boolean87 = path81.equals(path85);
        boolean boolean88 = path74.equals(path81);
        boolean boolean89 = path72.equals(path74);
        boolean boolean90 = path62.equals(path74);
        boolean boolean91 = path11.equals(path62);
        boolean boolean92 = path1.equals(path62);
        org.junit.Assert.assertTrue("'" + boolean2 + "' != '" + true + "'", boolean2 == true);
        org.junit.Assert.assertTrue("'" + boolean5 + "' != '" + true + "'", boolean5 == true);
        org.junit.Assert.assertTrue("'" + boolean8 + "' != '" + true + "'", boolean8 == true);
        org.junit.Assert.assertTrue("'" + boolean9 + "' != '" + true + "'", boolean9 == true);
        org.junit.Assert.assertTrue("'" + boolean10 + "' != '" + true + "'", boolean10 == true);
        org.junit.Assert.assertTrue("'" + boolean14 + "' != '" + true + "'", boolean14 == true);
        org.junit.Assert.assertTrue("'" + boolean17 + "' != '" + true + "'", boolean17 == true);
        org.junit.Assert.assertTrue("'" + boolean20 + "' != '" + true + "'", boolean20 == true);
        org.junit.Assert.assertTrue("'" + boolean21 + "' != '" + true + "'", boolean21 == true);
        org.junit.Assert.assertTrue("'" + boolean24 + "' != '" + true + "'", boolean24 == true);
        org.junit.Assert.assertTrue("'" + boolean27 + "' != '" + true + "'", boolean27 == true);
        org.junit.Assert.assertTrue("'" + boolean28 + "' != '" + true + "'", boolean28 == true);
        org.junit.Assert.assertTrue("'" + boolean29 + "' != '" + true + "'", boolean29 == true);
        org.junit.Assert.assertTrue("'" + boolean30 + "' != '" + true + "'", boolean30 == true);
        org.junit.Assert.assertTrue("'" + boolean31 + "' != '" + true + "'", boolean31 == true);
        org.junit.Assert.assertTrue("'" + boolean34 + "' != '" + true + "'", boolean34 == true);
        org.junit.Assert.assertTrue("'" + boolean37 + "' != '" + true + "'", boolean37 == true);
        org.junit.Assert.assertTrue("'" + boolean38 + "' != '" + true + "'", boolean38 == true);
        org.junit.Assert.assertTrue("'" + boolean41 + "' != '" + true + "'", boolean41 == true);
        org.junit.Assert.assertTrue("'" + boolean44 + "' != '" + true + "'", boolean44 == true);
        org.junit.Assert.assertTrue("'" + boolean45 + "' != '" + true + "'", boolean45 == true);
        org.junit.Assert.assertTrue("'" + boolean46 + "' != '" + true + "'", boolean46 == true);
        org.junit.Assert.assertTrue("'" + boolean47 + "' != '" + true + "'", boolean47 == true);
        org.junit.Assert.assertTrue("'" + boolean50 + "' != '" + true + "'", boolean50 == true);
        org.junit.Assert.assertTrue("'" + boolean51 + "' != '" + true + "'", boolean51 == true);
        org.junit.Assert.assertTrue("'" + boolean54 + "' != '" + true + "'", boolean54 == true);
        org.junit.Assert.assertTrue("'" + boolean57 + "' != '" + true + "'", boolean57 == true);
        org.junit.Assert.assertTrue("'" + boolean60 + "' != '" + true + "'", boolean60 == true);
        org.junit.Assert.assertTrue("'" + boolean61 + "' != '" + true + "'", boolean61 == true);
        org.junit.Assert.assertTrue("'" + boolean64 + "' != '" + true + "'", boolean64 == true);
        org.junit.Assert.assertTrue("'" + boolean67 + "' != '" + true + "'", boolean67 == true);
        org.junit.Assert.assertTrue("'" + boolean68 + "' != '" + true + "'", boolean68 == true);
        org.junit.Assert.assertTrue("'" + boolean69 + "' != '" + true + "'", boolean69 == true);
        org.junit.Assert.assertTrue("'" + boolean70 + "' != '" + true + "'", boolean70 == true);
        org.junit.Assert.assertTrue("'" + boolean73 + "' != '" + true + "'", boolean73 == true);
        org.junit.Assert.assertTrue("'" + boolean76 + "' != '" + true + "'", boolean76 == true);
        org.junit.Assert.assertTrue("'" + boolean79 + "' != '" + true + "'", boolean79 == true);
        org.junit.Assert.assertTrue("'" + boolean80 + "' != '" + true + "'", boolean80 == true);
        org.junit.Assert.assertTrue("'" + boolean83 + "' != '" + true + "'", boolean83 == true);
        org.junit.Assert.assertTrue("'" + boolean86 + "' != '" + true + "'", boolean86 == true);
        org.junit.Assert.assertTrue("'" + boolean87 + "' != '" + true + "'", boolean87 == true);
        org.junit.Assert.assertTrue("'" + boolean88 + "' != '" + true + "'", boolean88 == true);
        org.junit.Assert.assertTrue("'" + boolean89 + "' != '" + true + "'", boolean89 == true);
        org.junit.Assert.assertTrue("'" + boolean90 + "' != '" + true + "'", boolean90 == true);
        org.junit.Assert.assertTrue("'" + boolean91 + "' != '" + true + "'", boolean91 == true);
        org.junit.Assert.assertTrue("'" + boolean92 + "' != '" + true + "'", boolean92 == true);
    }
}

