import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest20 {

    public static boolean debug = false;

    @Test
    public void test21() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest20.test21");
        org.graphstream.graph.Path path0 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path1 = new org.graphstream.graph.Path();
        boolean boolean2 = path0.equals(path1);
        org.graphstream.graph.Path path3 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path4 = new org.graphstream.graph.Path();
        boolean boolean5 = path3.equals(path4);
        org.graphstream.graph.Path path6 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path7 = new org.graphstream.graph.Path();
        boolean boolean8 = path6.equals(path7);
        boolean boolean9 = path3.equals(path7);
        org.graphstream.graph.Path path10 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path11 = new org.graphstream.graph.Path();
        boolean boolean12 = path10.equals(path11);
        org.graphstream.graph.Path path13 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path14 = new org.graphstream.graph.Path();
        boolean boolean15 = path13.equals(path14);
        boolean boolean16 = path10.equals(path14);
        boolean boolean17 = path3.equals(path10);
        boolean boolean18 = path1.equals(path3);
        org.graphstream.graph.Path path19 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path20 = new org.graphstream.graph.Path();
        boolean boolean21 = path19.equals(path20);
        org.graphstream.graph.Path path22 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path23 = new org.graphstream.graph.Path();
        boolean boolean24 = path22.equals(path23);
        org.graphstream.graph.Path path25 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path26 = new org.graphstream.graph.Path();
        boolean boolean27 = path25.equals(path26);
        boolean boolean28 = path22.equals(path26);
        org.graphstream.graph.Path path29 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path30 = new org.graphstream.graph.Path();
        boolean boolean31 = path29.equals(path30);
        org.graphstream.graph.Path path32 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path33 = new org.graphstream.graph.Path();
        boolean boolean34 = path32.equals(path33);
        boolean boolean35 = path29.equals(path33);
        boolean boolean36 = path22.equals(path29);
        boolean boolean37 = path20.equals(path22);
        boolean boolean38 = path1.equals(path20);
        org.graphstream.graph.Path path39 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path40 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path41 = new org.graphstream.graph.Path();
        boolean boolean42 = path40.equals(path41);
        org.graphstream.graph.Path path43 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path44 = new org.graphstream.graph.Path();
        boolean boolean45 = path43.equals(path44);
        org.graphstream.graph.Path path46 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path47 = new org.graphstream.graph.Path();
        boolean boolean48 = path46.equals(path47);
        boolean boolean49 = path43.equals(path47);
        org.graphstream.graph.Path path50 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path51 = new org.graphstream.graph.Path();
        boolean boolean52 = path50.equals(path51);
        org.graphstream.graph.Path path53 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path54 = new org.graphstream.graph.Path();
        boolean boolean55 = path53.equals(path54);
        boolean boolean56 = path50.equals(path54);
        boolean boolean57 = path43.equals(path50);
        boolean boolean58 = path41.equals(path50);
        boolean boolean59 = path39.equals(path41);
        org.graphstream.graph.Path path60 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path61 = new org.graphstream.graph.Path();
        boolean boolean62 = path60.equals(path61);
        org.graphstream.graph.Path path63 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path64 = new org.graphstream.graph.Path();
        boolean boolean65 = path63.equals(path64);
        boolean boolean66 = path60.equals(path64);
        org.graphstream.graph.Path path67 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path68 = new org.graphstream.graph.Path();
        boolean boolean69 = path67.equals(path68);
        org.graphstream.graph.Path path70 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path71 = new org.graphstream.graph.Path();
        boolean boolean72 = path70.equals(path71);
        boolean boolean73 = path67.equals(path71);
        boolean boolean74 = path64.equals(path71);
        org.graphstream.graph.Path path75 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path76 = new org.graphstream.graph.Path();
        boolean boolean77 = path75.equals(path76);
        boolean boolean78 = path71.equals(path75);
        boolean boolean79 = path41.equals(path75);
        boolean boolean80 = path1.equals(path41);
        org.graphstream.graph.Path path81 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path82 = new org.graphstream.graph.Path();
        boolean boolean83 = path81.equals(path82);
        org.graphstream.graph.Path path84 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path85 = new org.graphstream.graph.Path();
        boolean boolean86 = path84.equals(path85);
        org.graphstream.graph.Path path87 = new org.graphstream.graph.Path();
        org.graphstream.graph.Path path88 = new org.graphstream.graph.Path();
        boolean boolean89 = path87.equals(path88);
        boolean boolean90 = path84.equals(path88);
        boolean boolean91 = path82.equals(path84);
        boolean boolean92 = path41.equals(path84);
        org.junit.Assert.assertTrue("'" + boolean2 + "' != '" + true + "'", boolean2 == true);
        org.junit.Assert.assertTrue("'" + boolean5 + "' != '" + true + "'", boolean5 == true);
        org.junit.Assert.assertTrue("'" + boolean8 + "' != '" + true + "'", boolean8 == true);
        org.junit.Assert.assertTrue("'" + boolean9 + "' != '" + true + "'", boolean9 == true);
        org.junit.Assert.assertTrue("'" + boolean12 + "' != '" + true + "'", boolean12 == true);
        org.junit.Assert.assertTrue("'" + boolean15 + "' != '" + true + "'", boolean15 == true);
        org.junit.Assert.assertTrue("'" + boolean16 + "' != '" + true + "'", boolean16 == true);
        org.junit.Assert.assertTrue("'" + boolean17 + "' != '" + true + "'", boolean17 == true);
        org.junit.Assert.assertTrue("'" + boolean18 + "' != '" + true + "'", boolean18 == true);
        org.junit.Assert.assertTrue("'" + boolean21 + "' != '" + true + "'", boolean21 == true);
        org.junit.Assert.assertTrue("'" + boolean24 + "' != '" + true + "'", boolean24 == true);
        org.junit.Assert.assertTrue("'" + boolean27 + "' != '" + true + "'", boolean27 == true);
        org.junit.Assert.assertTrue("'" + boolean28 + "' != '" + true + "'", boolean28 == true);
        org.junit.Assert.assertTrue("'" + boolean31 + "' != '" + true + "'", boolean31 == true);
        org.junit.Assert.assertTrue("'" + boolean34 + "' != '" + true + "'", boolean34 == true);
        org.junit.Assert.assertTrue("'" + boolean35 + "' != '" + true + "'", boolean35 == true);
        org.junit.Assert.assertTrue("'" + boolean36 + "' != '" + true + "'", boolean36 == true);
        org.junit.Assert.assertTrue("'" + boolean37 + "' != '" + true + "'", boolean37 == true);
        org.junit.Assert.assertTrue("'" + boolean38 + "' != '" + true + "'", boolean38 == true);
        org.junit.Assert.assertTrue("'" + boolean42 + "' != '" + true + "'", boolean42 == true);
        org.junit.Assert.assertTrue("'" + boolean45 + "' != '" + true + "'", boolean45 == true);
        org.junit.Assert.assertTrue("'" + boolean48 + "' != '" + true + "'", boolean48 == true);
        org.junit.Assert.assertTrue("'" + boolean49 + "' != '" + true + "'", boolean49 == true);
        org.junit.Assert.assertTrue("'" + boolean52 + "' != '" + true + "'", boolean52 == true);
        org.junit.Assert.assertTrue("'" + boolean55 + "' != '" + true + "'", boolean55 == true);
        org.junit.Assert.assertTrue("'" + boolean56 + "' != '" + true + "'", boolean56 == true);
        org.junit.Assert.assertTrue("'" + boolean57 + "' != '" + true + "'", boolean57 == true);
        org.junit.Assert.assertTrue("'" + boolean58 + "' != '" + true + "'", boolean58 == true);
        org.junit.Assert.assertTrue("'" + boolean59 + "' != '" + true + "'", boolean59 == true);
        org.junit.Assert.assertTrue("'" + boolean62 + "' != '" + true + "'", boolean62 == true);
        org.junit.Assert.assertTrue("'" + boolean65 + "' != '" + true + "'", boolean65 == true);
        org.junit.Assert.assertTrue("'" + boolean66 + "' != '" + true + "'", boolean66 == true);
        org.junit.Assert.assertTrue("'" + boolean69 + "' != '" + true + "'", boolean69 == true);
        org.junit.Assert.assertTrue("'" + boolean72 + "' != '" + true + "'", boolean72 == true);
        org.junit.Assert.assertTrue("'" + boolean73 + "' != '" + true + "'", boolean73 == true);
        org.junit.Assert.assertTrue("'" + boolean74 + "' != '" + true + "'", boolean74 == true);
        org.junit.Assert.assertTrue("'" + boolean77 + "' != '" + true + "'", boolean77 == true);
        org.junit.Assert.assertTrue("'" + boolean78 + "' != '" + true + "'", boolean78 == true);
        org.junit.Assert.assertTrue("'" + boolean79 + "' != '" + true + "'", boolean79 == true);
        org.junit.Assert.assertTrue("'" + boolean80 + "' != '" + true + "'", boolean80 == true);
        org.junit.Assert.assertTrue("'" + boolean83 + "' != '" + true + "'", boolean83 == true);
        org.junit.Assert.assertTrue("'" + boolean86 + "' != '" + true + "'", boolean86 == true);
        org.junit.Assert.assertTrue("'" + boolean89 + "' != '" + true + "'", boolean89 == true);
        org.junit.Assert.assertTrue("'" + boolean90 + "' != '" + true + "'", boolean90 == true);
        org.junit.Assert.assertTrue("'" + boolean91 + "' != '" + true + "'", boolean91 == true);
        org.junit.Assert.assertTrue("'" + boolean92 + "' != '" + true + "'", boolean92 == true);
    }
}

