/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 06 13:04:23 GMT 2023
 */

package cern.colt.matrix.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cern.colt.matrix.DoubleMatrix2D;
import cern.colt.matrix.impl.DenseDoubleMatrix1D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DenseDoubleMatrix1D_ESTest_2 extends DenseDoubleMatrix1D_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      double[] doubleArray0 = new double[8];
      DenseDoubleMatrix1D denseDoubleMatrix1D0 = new DenseDoubleMatrix1D(doubleArray0);
      DoubleMatrix2D doubleMatrix2D0 = denseDoubleMatrix1D0.like2D(9, 3);
      assertEquals(27, doubleMatrix2D0.size());
  }
}
