import org.elasticsearch.action.index.*;
import org.elasticsearch.ElasticsearchGenerationException;
import org.elasticsearch.Version;
import org.elasticsearch.action.ActionRequestValidationException;
import org.elasticsearch.action.CompositeIndicesRequest;
import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.RoutingMissingException;
import org.elasticsearch.action.support.replication.ReplicatedWriteRequest;
import org.elasticsearch.action.support.replication.ReplicationRequest;
import org.elasticsearch.client.Requests;
import org.elasticsearch.cluster.metadata.MappingMetaData;
import org.elasticsearch.cluster.metadata.MetaData;
import org.elasticsearch.common.Nullable;
import org.elasticsearch.common.UUIDs;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.io.stream.StreamOutput;
import org.elasticsearch.common.lucene.uid.Versions;
import org.elasticsearch.common.unit.ByteSizeValue;
import org.elasticsearch.common.unit.TimeValue;
import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.common.xcontent.XContentFactory;
import org.elasticsearch.common.xcontent.XContentHelper;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.IndexSettings;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.shard.ShardId;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import static org.elasticsearch.action.ValidateActions.addValidationError;
import java.util.*;

import org.elasticsearch.Version;
import org.elasticsearch.action.ActionRequestValidationException;
import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.support.ActiveShardCount;
import org.elasticsearch.action.support.replication.ReplicationResponse;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.io.stream.BytesStreamOutput;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.unit.ByteSizeValue;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.seqno.SequenceNumbers;
import org.elasticsearch.index.shard.ShardId;
import org.elasticsearch.rest.RestStatus;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import static org.junit.Assert.*;
import org.junit.Test;

import org.junit.*;


public class CodexTest_0_4_5 { 
  @Test
    public void testParent() {
        String temp = "temp";
        String temp2 = "temp2";
        String temp3 = "temp3";
        String temp4 = "temp4";
        String temp5 = "temp5";
        String temp6 = "temp6";
        String temp7 = "temp7";
        String temp8 = "temp8";
        String temp9 = "temp9";
        String temp10 = "temp10";
        String temp11 = "temp11";
        String temp12 = "temp12";
        String temp13 = "temp13";
        String temp14 = "temp14";
        String temp15 = "temp15";
        String temp16 = "temp16";
        String temp17 = "temp17";
        String temp18 = "temp18";
        String temp19 = "temp19";
        String temp20 = "temp20";
        String temp21 = "temp21";
        String temp22 = "temp22";
        String temp23 = "temp23";
        String temp24 = "temp24";
        String temp25 = "temp25";
        String temp26 = "temp26";
        String temp27 = "temp27";
        String temp28 = "temp28";
        String temp29 = "temp29";
        String temp30 = "temp30";
        String temp31 = "temp31";
        String temp32 = "temp32";
        String temp33 = "temp33";
        String temp34 = "temp34";
        String temp35 = "temp35";
        String temp36 = "temp36";
        String temp37 = "temp37";
        String temp38 = "temp38";
        String temp39 = "temp39";
        String temp40 = "temp40";
        String temp41 = "temp41";
        String temp42 = "temp42";
        String temp43 = "temp43";
        String temp44 = "temp44";
        String temp45 = "temp45";
        String temp46 = "temp46";
        String temp47 = "temp47";
        String temp48 = "temp48";
        String temp49 = "temp49";
        String temp50
}