/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 22 08:48:21 GMT 2022
 */

package newjdkname;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import newjdkname.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ArrayList_ESTest_1 extends ArrayList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArrayList<Object> arrayList0 = null;
      try {
        arrayList0 = new ArrayList<Object>((-1226));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1226
         //
         verifyException("newjdkname.ArrayList", e);
      }
  }
}
