import org.elasticsearch.action.index.*;
import org.elasticsearch.ElasticsearchGenerationException;
import org.elasticsearch.Version;
import org.elasticsearch.action.ActionRequestValidationException;
import org.elasticsearch.action.CompositeIndicesRequest;
import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.RoutingMissingException;
import org.elasticsearch.action.support.replication.ReplicatedWriteRequest;
import org.elasticsearch.action.support.replication.ReplicationRequest;
import org.elasticsearch.client.Requests;
import org.elasticsearch.cluster.metadata.MappingMetaData;
import org.elasticsearch.cluster.metadata.MetaData;
import org.elasticsearch.common.Nullable;
import org.elasticsearch.common.UUIDs;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.io.stream.StreamOutput;
import org.elasticsearch.common.lucene.uid.Versions;
import org.elasticsearch.common.unit.ByteSizeValue;
import org.elasticsearch.common.unit.TimeValue;
import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.common.xcontent.XContentFactory;
import org.elasticsearch.common.xcontent.XContentHelper;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.IndexSettings;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.shard.ShardId;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import static org.elasticsearch.action.ValidateActions.addValidationError;
import java.util.*;

import org.elasticsearch.Version;
import org.elasticsearch.action.ActionRequestValidationException;
import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.support.ActiveShardCount;
import org.elasticsearch.action.support.replication.ReplicationResponse;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.io.stream.BytesStreamOutput;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.unit.ByteSizeValue;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.seqno.SequenceNumbers;
import org.elasticsearch.index.shard.ShardId;
import org.elasticsearch.rest.RestStatus;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import static org.junit.Assert.*;
import org.junit.Test;

import org.junit.*;


public class CodexTest_0_3_13 { 
  @Test
    public void testParent() {
        String parent = "parent";
        String name = "name";
        String path = "path";
        String fullPath = "fullPath";
        String uri = "uri";
        String index = "index";
        String type = "type";
        long version = 1L;
        long seqNo = 2L;
        long primaryTerm = 3L;
        long versionType = 4L;
        long id = 5L;
        long sourceAsMap = 6L;
        long fields = 7L;
        long highlightFields = 8L;
        long sortValues = 9L;
        long matchedQueries = 10L;
        long innerHits = 11L;
        long shard = 12L;
        long source = 13L;
        long get = 14L;
        long exists = 15L;
        long explanation = 16L;
        long highlightFields = 17L;
        long matchedQueries = 18L;
        long sortValues = 19L;
        long innerHits = 20L;
        long shard = 21L;
        long source = 22L;
        long get = 23L;
        long exists = 24L;
        long explanation = 25L;
        long highlightFields = 26L;
        long matchedQueries = 27L;
        long sortValues = 28L;
        long innerHits = 29L;
        long shard = 30L;
        long source = 31L;
        long get = 32L;
        long exists = 33L;
        long explanation = 34L;
        long highlightFields = 35L;
        long matchedQueries = 36L;
        long sortValues = 37L;
        long innerHits = 38L;
        long shard = 39L;
        long source = 40L;
        long get = 41L;
        long exists = 42L;
        long explanation = 43L;
        long highlightFields = 44L;
        long matchedQueries = 45L;
        long sortValues = 46L;
        long innerHits = 47L;
        long shard = 48L;
        long source
}