/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 12 07:34:30 GMT 2022
 */

package weka.core;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockRandom;
import org.junit.runner.RunWith;
import weka.core.AlgVector;
import weka.core.Attribute;
import weka.core.BinarySparseInstance;
import weka.core.Instance;
import weka.core.Instances;
import weka.core.SparseInstance;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class AlgVector_ESTest_4 extends AlgVector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AlgVector algVector0 = new AlgVector(110);
      int int0 = algVector0.numElements();
      assertEquals(110, int0);
      assertEquals(0.0, algVector0.norm(), 0.01);
  }
}
