/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 12 06:51:41 GMT 2022
 */

package org.graphstream.graph;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.EmptyStackException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Path;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Path_ESTest_3 extends Path_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Path path0 = new Path();
      boolean boolean0 = path0.contains((Edge) null);
      assertFalse(boolean0);
  }
}
