/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 12 06:51:41 GMT 2022
 */

package org.graphstream.graph;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.EmptyStackException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Path;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Path_ESTest_2 extends Path_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Path path0 = new Path();
      // Undeclared exception!
      try { 
        path0.popEdge();
        fail("Expecting exception: EmptyStackException");
      
      } catch(EmptyStackException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Stack", e);
      }
  }
}
