#!/bin/bash

PACKAGE="$1"
CLASS_NAME="$2"
SOURCE="$3"
OUTPUT_PATH="$4"

DEPENDENCIES="../dependencies/junit-4.13.2.jar:../dependencies/hamcrest-core-1.3.jar/":../dependencies/joda-time-2.9.8.jar:../dependencies/lucene-core-7.2.0.jar:../dependencies/javax.persistence-api-2.2.jar:../dependencies/gwt-dev-2.5.1.jar:../dependencies/gwt-servlet-2.5.1.jar
COLT_CP="../../../projects/colt.jar"
ELASTICSEARCH_CP="../../../projects/elasticsearch-6.1.1.jar"
GWT_CP="../../../projects/gwt-user-2.5.1.jar"
GRAPHSTREAM_CP="../../../projects/gs-core-1.3.jar"
GUAVA_CP="../../../projects/guava-19.0.jar"
HIBERNATE_CP="../../../projects/hibernate-core-5.4.2.Final.jar"
MATH_CP="../../../projects/commons-math3-3.6.1.jar"
WEKA_CP="../../../projects/weka-stable-3.8.0.jar"

java -classpath ./target/classes/:$DEPENDENCIES:$COLT_CP:$ELASTICSEARCH_CP:$GRAPHSTREAM_CP:$GWT_CP:$GUAVA_CP:$HIBERNATE_CP:$MATH_CP:$WEKA_CP compile_utils.Main "${PACKAGE}" "${CLASS_NAME}" "${SOURCE}" "${OUTPUT_PATH}"