/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 12 07:06:25 GMT 2022
 */

package org.hibernate.type.descriptor.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.hibernate.type.descriptor.java.BooleanTypeDescriptor;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class BooleanTypeDescriptor_ESTest_3 extends BooleanTypeDescriptor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BooleanTypeDescriptor booleanTypeDescriptor0 = new BooleanTypeDescriptor();
      Boolean boolean0 = Boolean.FALSE;
      Short short0 = booleanTypeDescriptor0.toShort(boolean0);
      assertEquals((short)0, (short)short0);
  }
}
