/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 12 07:21:57 GMT 2022
 */

package org.apache.commons.math3.geometry.euclidean.oned;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math3.geometry.euclidean.oned.Vector1D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Vector1D_ESTest_2 extends Vector1D_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Vector1D vector1D0 = Vector1D.ZERO;
      Vector1D vector1D1 = new Vector1D(1271.72427645257, vector1D0, 1271.72427645257, vector1D0);
      Vector1D vector1D2 = new Vector1D((-819.573), vector1D1, 0.0, vector1D0, (-1.0), vector1D1, 0.0, vector1D0);
      assertEquals(0.0, vector1D2.getNormSq(), 0.01);
  }
}
