/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 12 07:21:57 GMT 2022
 */

package org.apache.commons.math3.geometry.euclidean.oned;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math3.geometry.euclidean.oned.Vector1D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Vector1D_ESTest_11 extends Vector1D_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Vector1D vector1D0 = new Vector1D((-1.0));
      // Undeclared exception!
      try { 
        Vector1D.distanceSq((Vector1D) null, vector1D0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.geometry.euclidean.oned.Vector1D", e);
      }
  }
}
