import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest0 {

    public static boolean debug = false;

    @Test
    public void test1() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test1");
        org.elasticsearch.action.index.IndexRequest indexRequest0 = new org.elasticsearch.action.index.IndexRequest();
        java.lang.String str1 = indexRequest0.parent();
        java.lang.String str2 = indexRequest0.parent();
        java.lang.String str3 = indexRequest0.parent();
        java.lang.String str4 = indexRequest0.parent();
        java.lang.String str5 = indexRequest0.parent();
        java.lang.String str6 = indexRequest0.parent();
        java.lang.String str7 = indexRequest0.parent();
        java.lang.String str8 = indexRequest0.parent();
        java.lang.String str9 = indexRequest0.parent();
        java.lang.String str10 = indexRequest0.parent();
        java.lang.String str11 = indexRequest0.parent();
        java.lang.String str12 = indexRequest0.parent();
        java.lang.String str13 = indexRequest0.parent();
        java.lang.String str14 = indexRequest0.parent();
        java.lang.String str15 = indexRequest0.parent();
        java.lang.String str16 = indexRequest0.parent();
        java.lang.String str17 = indexRequest0.parent();
        java.lang.String str18 = indexRequest0.parent();
        java.lang.String str19 = indexRequest0.parent();
        java.lang.String str20 = indexRequest0.parent();
        java.lang.String str21 = indexRequest0.parent();
        java.lang.String str22 = indexRequest0.parent();
        java.lang.String str23 = indexRequest0.parent();
        java.lang.String str24 = indexRequest0.parent();
        java.lang.String str25 = indexRequest0.parent();
        java.lang.String str26 = indexRequest0.parent();
        java.lang.String str27 = indexRequest0.parent();
        java.lang.String str28 = indexRequest0.parent();
        java.lang.String str29 = indexRequest0.parent();
        java.lang.String str30 = indexRequest0.parent();
        java.lang.String str31 = indexRequest0.parent();
        java.lang.String str32 = indexRequest0.parent();
        java.lang.String str33 = indexRequest0.parent();
        java.lang.String str34 = indexRequest0.parent();
        java.lang.String str35 = indexRequest0.parent();
        java.lang.String str36 = indexRequest0.parent();
        java.lang.String str37 = indexRequest0.parent();
        java.lang.String str38 = indexRequest0.parent();
        java.lang.String str39 = indexRequest0.parent();
        java.lang.String str40 = indexRequest0.parent();
        java.lang.String str41 = indexRequest0.parent();
        java.lang.String str42 = indexRequest0.parent();
        java.lang.String str43 = indexRequest0.parent();
        java.lang.String str44 = indexRequest0.parent();
        java.lang.String str45 = indexRequest0.parent();
        java.lang.String str46 = indexRequest0.parent();
        java.lang.String str47 = indexRequest0.parent();
        java.lang.String str48 = indexRequest0.parent();
        java.lang.String str49 = indexRequest0.parent();
        java.lang.String str50 = indexRequest0.parent();
        java.lang.String str51 = indexRequest0.parent();
        java.lang.String str52 = indexRequest0.parent();
        java.lang.String str53 = indexRequest0.parent();
        java.lang.String str54 = indexRequest0.parent();
        java.lang.String str55 = indexRequest0.parent();
        java.lang.String str56 = indexRequest0.parent();
        java.lang.String str57 = indexRequest0.parent();
        java.lang.String str58 = indexRequest0.parent();
        java.lang.String str59 = indexRequest0.parent();
        java.lang.String str60 = indexRequest0.parent();
        java.lang.String str61 = indexRequest0.parent();
        java.lang.String str62 = indexRequest0.parent();
        java.lang.String str63 = indexRequest0.parent();
        java.lang.String str64 = indexRequest0.parent();
        java.lang.String str65 = indexRequest0.parent();
        java.lang.String str66 = indexRequest0.parent();
        java.lang.String str67 = indexRequest0.parent();
        java.lang.String str68 = indexRequest0.parent();
        java.lang.String str69 = indexRequest0.parent();
        java.lang.String str70 = indexRequest0.parent();
        java.lang.String str71 = indexRequest0.parent();
        java.lang.String str72 = indexRequest0.parent();
        java.lang.String str73 = indexRequest0.parent();
        java.lang.String str74 = indexRequest0.parent();
        java.lang.String str75 = indexRequest0.parent();
        java.lang.String str76 = indexRequest0.parent();
        java.lang.String str77 = indexRequest0.parent();
        java.lang.String str78 = indexRequest0.parent();
        java.lang.String str79 = indexRequest0.parent();
        java.lang.String str80 = indexRequest0.parent();
        java.lang.String str81 = indexRequest0.parent();
        java.lang.String str82 = indexRequest0.parent();
        java.lang.String str83 = indexRequest0.parent();
        java.lang.String str84 = indexRequest0.parent();
        java.lang.String str85 = indexRequest0.parent();
        java.lang.String str86 = indexRequest0.parent();
        java.lang.String str87 = indexRequest0.parent();
        java.lang.String str88 = indexRequest0.parent();
        java.lang.String str89 = indexRequest0.parent();
        java.lang.String str90 = indexRequest0.parent();
        java.lang.String str91 = indexRequest0.parent();
        java.lang.String str92 = indexRequest0.parent();
        java.lang.String str93 = indexRequest0.parent();
        java.lang.String str94 = indexRequest0.parent();
        java.lang.String str95 = indexRequest0.parent();
        java.lang.String str96 = indexRequest0.parent();
        java.lang.String str97 = indexRequest0.parent();
        java.lang.String str98 = indexRequest0.parent();
        org.junit.Assert.assertNull(str1);
        org.junit.Assert.assertNull(str2);
        org.junit.Assert.assertNull(str3);
        org.junit.Assert.assertNull(str4);
        org.junit.Assert.assertNull(str5);
        org.junit.Assert.assertNull(str6);
        org.junit.Assert.assertNull(str7);
        org.junit.Assert.assertNull(str8);
        org.junit.Assert.assertNull(str9);
        org.junit.Assert.assertNull(str10);
        org.junit.Assert.assertNull(str11);
        org.junit.Assert.assertNull(str12);
        org.junit.Assert.assertNull(str13);
        org.junit.Assert.assertNull(str14);
        org.junit.Assert.assertNull(str15);
        org.junit.Assert.assertNull(str16);
        org.junit.Assert.assertNull(str17);
        org.junit.Assert.assertNull(str18);
        org.junit.Assert.assertNull(str19);
        org.junit.Assert.assertNull(str20);
        org.junit.Assert.assertNull(str21);
        org.junit.Assert.assertNull(str22);
        org.junit.Assert.assertNull(str23);
        org.junit.Assert.assertNull(str24);
        org.junit.Assert.assertNull(str25);
        org.junit.Assert.assertNull(str26);
        org.junit.Assert.assertNull(str27);
        org.junit.Assert.assertNull(str28);
        org.junit.Assert.assertNull(str29);
        org.junit.Assert.assertNull(str30);
        org.junit.Assert.assertNull(str31);
        org.junit.Assert.assertNull(str32);
        org.junit.Assert.assertNull(str33);
        org.junit.Assert.assertNull(str34);
        org.junit.Assert.assertNull(str35);
        org.junit.Assert.assertNull(str36);
        org.junit.Assert.assertNull(str37);
        org.junit.Assert.assertNull(str38);
        org.junit.Assert.assertNull(str39);
        org.junit.Assert.assertNull(str40);
        org.junit.Assert.assertNull(str41);
        org.junit.Assert.assertNull(str42);
        org.junit.Assert.assertNull(str43);
        org.junit.Assert.assertNull(str44);
        org.junit.Assert.assertNull(str45);
        org.junit.Assert.assertNull(str46);
        org.junit.Assert.assertNull(str47);
        org.junit.Assert.assertNull(str48);
        org.junit.Assert.assertNull(str49);
        org.junit.Assert.assertNull(str50);
        org.junit.Assert.assertNull(str51);
        org.junit.Assert.assertNull(str52);
        org.junit.Assert.assertNull(str53);
        org.junit.Assert.assertNull(str54);
        org.junit.Assert.assertNull(str55);
        org.junit.Assert.assertNull(str56);
        org.junit.Assert.assertNull(str57);
        org.junit.Assert.assertNull(str58);
        org.junit.Assert.assertNull(str59);
        org.junit.Assert.assertNull(str60);
        org.junit.Assert.assertNull(str61);
        org.junit.Assert.assertNull(str62);
        org.junit.Assert.assertNull(str63);
        org.junit.Assert.assertNull(str64);
        org.junit.Assert.assertNull(str65);
        org.junit.Assert.assertNull(str66);
        org.junit.Assert.assertNull(str67);
        org.junit.Assert.assertNull(str68);
        org.junit.Assert.assertNull(str69);
        org.junit.Assert.assertNull(str70);
        org.junit.Assert.assertNull(str71);
        org.junit.Assert.assertNull(str72);
        org.junit.Assert.assertNull(str73);
        org.junit.Assert.assertNull(str74);
        org.junit.Assert.assertNull(str75);
        org.junit.Assert.assertNull(str76);
        org.junit.Assert.assertNull(str77);
        org.junit.Assert.assertNull(str78);
        org.junit.Assert.assertNull(str79);
        org.junit.Assert.assertNull(str80);
        org.junit.Assert.assertNull(str81);
        org.junit.Assert.assertNull(str82);
        org.junit.Assert.assertNull(str83);
        org.junit.Assert.assertNull(str84);
        org.junit.Assert.assertNull(str85);
        org.junit.Assert.assertNull(str86);
        org.junit.Assert.assertNull(str87);
        org.junit.Assert.assertNull(str88);
        org.junit.Assert.assertNull(str89);
        org.junit.Assert.assertNull(str90);
        org.junit.Assert.assertNull(str91);
        org.junit.Assert.assertNull(str92);
        org.junit.Assert.assertNull(str93);
        org.junit.Assert.assertNull(str94);
        org.junit.Assert.assertNull(str95);
        org.junit.Assert.assertNull(str96);
        org.junit.Assert.assertNull(str97);
        org.junit.Assert.assertNull(str98);
    }
}

