import org.elasticsearch.action.index.*;
import org.elasticsearch.ElasticsearchGenerationException;
import org.elasticsearch.Version;
import org.elasticsearch.action.ActionRequestValidationException;
import org.elasticsearch.action.CompositeIndicesRequest;
import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.RoutingMissingException;
import org.elasticsearch.action.support.replication.ReplicatedWriteRequest;
import org.elasticsearch.action.support.replication.ReplicationRequest;
import org.elasticsearch.client.Requests;
import org.elasticsearch.cluster.metadata.MappingMetaData;
import org.elasticsearch.cluster.metadata.MetaData;
import org.elasticsearch.common.Nullable;
import org.elasticsearch.common.UUIDs;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.io.stream.StreamOutput;
import org.elasticsearch.common.lucene.uid.Versions;
import org.elasticsearch.common.unit.ByteSizeValue;
import org.elasticsearch.common.unit.TimeValue;
import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.common.xcontent.XContentFactory;
import org.elasticsearch.common.xcontent.XContentHelper;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.IndexSettings;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.shard.ShardId;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import static org.elasticsearch.action.ValidateActions.addValidationError;
import java.util.*;

import org.elasticsearch.Version;
import org.elasticsearch.action.ActionRequestValidationException;
import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.support.ActiveShardCount;
import org.elasticsearch.action.support.replication.ReplicationResponse;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.io.stream.BytesStreamOutput;
import org.elasticsearch.common.io.stream.StreamInput;
import org.elasticsearch.common.unit.ByteSizeValue;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.seqno.SequenceNumbers;
import org.elasticsearch.index.shard.ShardId;
import org.elasticsearch.rest.RestStatus;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import static org.junit.Assert.*;
import org.junit.Test;

import org.junit.*;


public class CodexTest_0_4_1 { 
  @Test
    public void testParent() {
        String parent = "parent";
        String name = "name";
        String path = "path";
        String fullPath = "fullPath";
        String uri = "uri";
        String index = "index";
        String type = "type";
        long version = 1L;
        long seqNo = 2L;
        long primaryTerm = 3L;
        long id = 4L;
        long sourceVersion = 5L;
        long routingVersion = 6L;
        long versionTypeVersion = 7L;
        long versionTypeSeqNo = 8L;
        long versionTypePrimaryTerm = 9L;
        long versionType = 10L;
        long versionTypeVersionSeqNo = 11L;
        long versionTypeVersionPrimaryTerm = 12L;
        long versionTypeVersion = 13L;
        long versionTypeSeqNoPrimaryTerm = 14L;
        long versionTypeSeqNo = 15L;
        long versionTypePrimaryTerm = 16L;
        long versionType = 17L;
        long versionTypeSeqNoPrimaryTerm = 18L;
        long versionTypeSeqNo = 19L;
        long versionTypePrimaryTerm = 20L;
        long versionType = 21L;
        long versionTypeVersionSeqNoPrimaryTerm = 22L;
        long versionTypeVersionSeqNo = 23L;
        long versionTypeVersionPrimaryTerm = 24L;
        long versionTypeVersion = 25L;
        long versionTypeSeqNoPrimaryTerm = 26L;
        long versionTypeSeqNo = 27L;
        long versionTypePrimaryTerm = 28L;
        long versionType = 29L;
        long versionTypeVersionSeqNoPrimaryTerm = 30L;
        long versionTypeVersionSeqNo = 31L;
        long versionTypeVersionPrimaryTerm = 32L;
        long versionTypeVersion = 33L;
        long versionTypeSeqNoPrimaryTerm = 34L;
        long versionTypeSeqNo = 35L;
        long versionTypePrimaryTerm = 36L;
        long versionType = 37L;
        long versionTypeVersionSeqNoPrimaryTerm = 38L;
        long versionTypeVersion
}